CREATE TABLE `users` (
	`id` INT(12) NOT NULL AUTO_INCREMENT,
	`fullname` VARCHAR(50) NOT NULL COMMENT 'First and Last Name',
	`gender` VARCHAR(6) NOT NULL COMMENT 'male or female',
	`username` VARCHAR(20) NOT NULL,
	`hashed_password` VARCHAR(255) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`modified_at` DATETIME on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE = InnoDB;